# Generated by Django 3.2.25 on 2025-04-01 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field_name',
            new_name='name',
        ),
    ]
