# Generated by Django 3.2.25 on 2025-04-05 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchapp', '0002_rename_field_name_mymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column1',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='column3',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
